services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - ./dump:/data/db  # <--- Change here to point MongoDB to use this as its data directory
