version: '6.0'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./dump:/dump
    networks:
      - mynetwork

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - mynetwork

  backend:
    # environment:
    #   - MONGO_CONNECTION_URL=mongodb://mongodb:27017/secure
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./packages/backend:/secure-arc/packages/backend

  # frontend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.frontend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./packages/frontend:/secure-arc/packages/frontend

volumes:
  mongodb_data:
  redis_data:

networks:
  mynetwork:
