version: '6.0' # Using version 6.0

services:
  mongodb:
    image: mongo:latest  # Use the official MongoDB image from Docker Hub
    container_name: mongodb_container
    ports:
      - "27017:27017"
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: yourpassword  # Please choose a secure password
    volumes:
      - mongodb_data:/data/db
      - ./dump:/dump
    networks:
      - mynetwork

  redis:
    image: redis:latest  # Use the official Redis image from Docker Hub
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - mynetwork

volumes:
  mongodb_data:
  redis_data:

networks:
  mynetwork:
