version: '6.0'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongodb_data:/mongodb_data
    networks:
      - mynetwork

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - mynetwork

  # backend:
  #   env_file: 
  #     - .env
  #   build:
  #     context: .
  #     dockerfile: micro-backend/express-server/Dockerfile
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - mongodb
  #     - redis
  #   volumes:
  #     - ./micro-backend/express-server:/secure-arc/micro-backend/express-server
  #   networks:
  #     - mynetwork

  # frontend:
  #   build:
  #     context: .
  #     dockerfile: packages/frontend/Dockerfile
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./packages/frontend:/secure-arc/packages/frontend
  #   networks:
  #     - mynetwork

  # nginx:
  #   image: nginx:latest
  #   container_name: nginx_container
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - frontend
  #     - backend
  #   networks:
  #     - mynetwork

  verdaccio:
    image: verdaccio/verdaccio:latest
    container_name: verdaccio_container
    ports:
      - "4873:4873"
    volumes:
      - ./verdaccio/conf:/verdaccio/conf
      - ./verdaccio/storage:/verdaccio/storage
      - ./verdaccio/plugins:/verdaccio/plugins
    networks:
      - mynetwork
    user: "1000:1000" # This specifies both user and group ID. Adjust if needed.

networks:
  mynetwork:
    driver: bridge

volumes:
  mongodb_data:
  redis_data:
